name: "Comment artifact link on Pull Request description"
author: "@PicoCentauri"
description: "Update PR description with a link to download an artifact"

branding:
  color: "gray-dark"
  icon: "paperclip"

inputs:
  name:
    description: "Name of the artifact to link."
    default: "artifact"
    required: false
  description:
    description: "Description of the artifact download link."
    default: "Download artifact for this pull request"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "PicoCentauri/comment-artifact"
        ref: "main"

    - name: "Comment on Pull Request with link to an artifact"
      uses: actions/github-script@v7
      with:
        script: |
          const inputs = {
            "name": "${{ inputs.name }}",
            "description": `${{ inputs.description }}`,
          }
          const script = require("./scripts/edit-description.js");
          await script({inputs, github, context});
